# Generated by Django 5.0.1 on 2024-01-22 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nyx_app", "0002_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="user_input",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nyx_app.userinput",
            ),
        ),
    ]
