# Generated by Django 5.0.1 on 2024-04-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nyx_app", "0003_alter_feedback_user_input"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
    ]
